// Generated by CoffeeScript 1.10.0
(function() {
  var Game, game,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Game = (function(superClass) {
    extend(Game, superClass);

    function Game() {}

    return Game;

  })(Phaser.State);

  game = new Phaser.Game(640, 320, Phaser.AUTO, 'game', this({
    preload: function() {
      return this.game.load.image('logo', 'arts/bubble.png');
    },
    create: function() {
      this.logo = this.game.add.sprite(this.game.world.centerX, this.game.world.centerY, 'logo');
      this.logo.anchor.x = 0.5;
      this.logo.anchor.y = 0.5;
      return this.logo.update = function() {
        return this.angle++;
      };
    },
    update: function() {
      return this.logo.angle++;
    }
  }));

  window.onload = function() {
    return new Game;
  };

}).call(this);
